export type Photo = {
  /** Path under /photos/ (file lives in public/photos/, generated by `npm run photos`). */
  src: string;
  /**
   * Describe what's actually in the frame — for screen readers and SEO.
   * I (Claude) can't see the images, so these are placeholder strings.
   * Replace each one with a real one-line description.
   */
  alt: string;
  /** Optional Russian alt. Falls back to `alt` if absent. */
  altRu?: string;
  width: number;
  height: number;
  place?: string;
  year?: number;
  /** First photo marked hero: true becomes the fullscreen background. */
  hero?: boolean;
};

/**
 * Photo grid order matches the array order. Edit freely:
 *   - reorder lines to change layout
 *   - move `hero: true` to whichever photo should fill the landing screen
 *   - delete entries to drop a photo (keep the file or `rm` it from public/photos/)
 *
 * To add new ones: drop originals into `photos-source/`, run `npm run photos`,
 * and paste new entries here.
 */
export const photos: Photo[] = [
  { src: '/photos/dsc-2654.jpg', alt: 'Photograph by Taras Volchenko', width: 2400, height: 1600 },
  { src: '/photos/dsc-0412.jpg', alt: 'Photograph by Taras Volchenko', width: 2400, height: 1607 },
  { src: '/photos/dsc-0998.jpg', alt: 'Photograph by Taras Volchenko', width: 1600, height: 2400 },
  { src: '/photos/dsc-2453.jpg', alt: 'Photograph by Taras Volchenko', width: 1600, height: 2400 },
  { src: '/photos/dsc-0926.jpg', alt: 'Photograph by Taras Volchenko', width: 2400, height: 1600, hero: true },
  { src: '/photos/pxl-20260508-150435753-raw-02-original.jpg', alt: 'Photograph by Taras Volchenko, May 2026', width: 1805, height: 2400, year: 2026 },
  { src: '/photos/dsc-1033.jpg', alt: 'Photograph by Taras Volchenko', width: 2400, height: 1600 },
  { src: '/photos/pxl-20260505-152229917-raw-02-original.jpg', alt: 'Photograph by Taras Volchenko, May 2026', width: 2400, height: 2400, year: 2026 },
  { src: '/photos/dsc-2411.jpg', alt: 'Photograph by Taras Volchenko', width: 2400, height: 1600 },
  { src: '/photos/dsc-0928.jpg', alt: 'Photograph by Taras Volchenko', width: 2400, height: 1600 },
  { src: '/photos/pxl-20260508-150633619-raw-02-original.jpg', alt: 'Photograph by Taras Volchenko, May 2026', width: 2400, height: 1805, year: 2026 },
  { src: '/photos/dsc-2505.jpg', alt: 'Photograph by Taras Volchenko', width: 2400, height: 1600 },
  { src: '/photos/dsc-2663.jpg', alt: 'Photograph by Taras Volchenko', width: 2400, height: 1600 },
  { src: '/photos/pxl-20260131-131714910-raw-02-original.jpg', alt: 'Photograph by Taras Volchenko, January 2026', width: 2400, height: 1897, year: 2026 },
];

/** No fallback — when no entry is marked `hero: true`, the hero stays text-only. */
export const heroPhoto = photos.find((p) => p.hero) ?? null;
export const gridPhotos = photos.filter((p) => !p.hero);
